# Generated by Django 5.2 on 2025-07-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['created_at'], 'verbose_name': 'Забег', 'verbose_name_plural': 'Забеги'},
        ),
    ]
