# Generated by Django 5.2 on 2025-07-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_alter_run_athlete_alter_run_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created_at'], 'verbose_name': 'Забег', 'verbose_name_plural': 'Забеги'},
        ),
    ]
