# Generated by Django 5.2 on 2025-08-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_athleteinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteinfo',
            options={'verbose_name': 'Информация об атлете', 'verbose_name_plural': 'Информация об атлетах'},
        ),
    ]
