# Generated by Django 5.2 on 2025-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_athleteinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(blank=True, verbose_name='Цели'),
        ),
    ]
