# Generated by Django 5.2 on 2025-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_alter_athleteinfo_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user',
            new_name='athlete',
        ),
    ]
