# Generated by Django 5.2 on 2025-08-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_rename_user_athleteinfo_athlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='athlete',
            new_name='user',
        ),
    ]
