# Generated by Django 5.2 on 2025-08-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_rename_athlete_athleteinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user',
            new_name='athlete',
        ),
    ]
