# Generated by Django 5.2 on 2025-08-10 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_alter_challenge_athlete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('full_name', 'athlete'), name='unique_challenge_per_athlete'),
        ),
    ]
