# Generated by Django 5.2 on 2025-08-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_challenge_unique_challenge_per_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Долгота')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_run.run', verbose_name='Забег')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
    ]
