# Generated by Django 5.2 on 2025-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Пройденная дистанция'),
        ),
    ]
