# Generated by Django 5.2 on 2025-08-26 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_alter_collectibleitem_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Атлеты'),
        ),
    ]
