# Generated by Django 5.2 on 2025-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_alter_collectibleitem_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Долгота'),
        ),
    ]
