# Generated by Django 5.2 on 2025-09-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0023_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Пройденная дистанция'),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость'),
        ),
    ]
