# Generated by Django 5.2 on 2025-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_position_distance_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Пройденная дистанция'),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Скорость'),
        ),
    ]
