# Generated by Django 5.2 on 2025-09-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0025_alter_position_distance_alter_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Средняя скорость'),
        ),
    ]
