# Generated by Django 5.2 on 2025-09-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0027_subscribe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_subscription',
        ),
    ]
